version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 2. to review
  - dependencies
  ignore:
  - dependency-name: com.gitlab.bitfireAT:dav4jvm
    versions:
    - "> 2.1.2"
    - "< 3"
  - dependency-name: org.apache.jackrabbit:jackrabbit-webdav
    versions:
    - "> 2.13.1"
    - "< 3"
  - dependency-name: org.apache.jackrabbit:jackrabbit-webdav
    versions:
    - "< 2.17.6"
    - ">= 2.17.5.a"
  - dependency-name: org.apache.jackrabbit:jackrabbit-webdav
    versions:
    - ">= 2.19.a"
    - "< 2.20"
